### ISSUE TITLE
Bug of Skill api "move_to"

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#2]
Hi~ 
Thanks for amazing work!

And I got a bug (maybe not) when using the "move_to" api like:

```bash
Skill `move_to 45 5` failed: No valid path found to reach position (45, 5)
```

Is this a bug or not? Will adding the `search` operation to `move_to` fix this bug?

**Comment by CommanderCero** [comment]
Hey,
Happy to hear that you like my work!

The _move_to_ skill does not explore the level. It is mainly intended for more fine-grained movement. If there is no known path to a location, the skill will fail and report this with the message you've seen. If you want to explore, I would recommend using the _explore_level_ skill.

Note that a skill failing is not an error unless it tells you that an exception occurred. A failed skill usually means what you want to do is not possible with that skill, and the resulting messages are used as feedback for the LLM agent.

The _search_ skill is just a thin wrapper around the search command in NetHack. So, it is used to find hidden walls/doors/traps, etc.

**Comment by Felixvillas** [comment]
> Hey, Happy to hear that you like my work!
> 
> The _move_to_ skill does not explore the level. It is mainly intended for more fine-grained movement. If there is no known path to a location, the skill will fail and report this with the message you've seen. If you want to explore, I would recommend using the _explore_level_ skill.
> 
> Note that a skill failing is not an error unless it tells you that an exception occurred. A failed skill usually means what you want to do is not possible with that skill, and the resulting messages are used as feedback for the LLM agent.
> 
> The _search_ skill is just a thin wrapper around the search command in NetHack. So, it is used to find hidden walls/doors/traps, etc.

I see. Thank you for your answer~
