### ISSUE TITLE
Is the skill `explore_level` will open the locked door?

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#3]
Hi~

I want to know if the `explore_level` skill will use an operation similar to `kick` to open locked doors?

If not, how can I insert the `kick` to the `explore_level` function?

Thanks!

**Comment by Felixvillas** [comment]
Oh! I found `open_neighbor_doors` in `explore_level`, I will study how it is implemented myself.

**Comment by CommanderCero** [comment]
Hey, the explore_level skill is almost an identical copy from the explore1 method defined in the autoascend agent.
By default the autoascend agent kicks open doors if they are locked, however this sometimes caused my agent to aggrevate shopkeepers. As such I've decided to remove this from the explore_level skill, which in retrospect was a bad idea (as the LLM just mostly ignores locked doors).

So feel free to use the autoascend implementation as inspiration:
https://github.com/maciej-sypetkowski/autoascend/blob/8527910bd85c4d851c18ad912aae606c92cd516a/autoascend/exploration_logic.py#L266

**Comment by Felixvillas** [comment]
Thanks！
I'll close this issue.
