### ISSUE TITLE
Bug when using `agent.get_path_to(x, y)`

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#4]
When I use `agent.get_path_to(x, y)`, I find that even if the position (x, y) is blocked, such as when the element at (x, y) is a wall or a boulder, `agent.get_path_to(x, y)` still returns a path instead of `None`.

Is this a bug? If so, could you please fix it?

**Comment by CommanderCero** [comment]
While unintuitive, this is actually intended.
Essentially get_path_to still returns a path if it can be reached OR if it is adjacent to a reachable tile.
This "feature" allows move_to for example to be used to open doors.
I agree that this could have been done in a much cleaner way, but I didn't have time to change it.

I also do not plan on updating this repo, as it would require a significant refactoring for which I do not have time.
As such, this repos main purpose is to serve as a reference for the methods and results described in my paper.
