### ISSUE TITLE
Eat/Drink from ground

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#5]
Hi~
It seems that [`eat/drink`](https://github.com/CommanderCero/NetPlay/blob/6487da46b357e17c1e1c96e67942363fff1393d6/netplay/nethack_agent/skills.py#L650) cannot be performed on the ground? If we want to operate on the ground units, we need at least to `press_key y`.

**Comment by CommanderCero** [comment]
Hey, yes most skills only do the bare minimum. In the case of eat/drink the skills only move you to the position and then execute the corresponding nethack command. Of course NetHack then asks if you are sure, which we let the LLM handle.

To reduce LLM calls it would be a good idea to handle this yourself, but there are edge-cases. For example if there are multiple food items on the ground it will ask you for every item if you want to eat it. Which is exactly the reason why I designed all the skills to only do the bare minimum, to let the LLM handle these edge-cases.
