### ISSUE TITLE
How to obtain information about death?

### ISSUE THREAD

**Issue by Felixvillas** [CommanderCero/NetPlay#7]
Hi~

I want to know how to obtain the information given by NetHack when an agent dies, such as: "You were killed by a large bat." / "You died from poisoning." / "You starved to death." ... and so on. Do you know how to get this information?

**Comment by CommanderCero** [comment]
There is a way to access that information but its quite hidden. Not sure if there is a easier way: https://github.com/CommanderCero/NetPlay/blob/6487da46b357e17c1e1c96e67942363fff1393d6/netplay/nethack_agent/agent.py#L120
